import { Instruction } from './types';

export const mockInstructions: Instruction[] = [
  {
    id: '1',
    name: 'Auto-approve small vendors',
    type: 'automation',
    status: 'Active',
    agent: 'Validation Agent',
    stage: 'Validation & Exceptions',
    processed: 1234,
    success: 1180,
    failed: 54,
    scope: 'Trusted vendors • Amount < 500',
    mode: 'Suggest',
    description: 'Automatically approve invoices under $500 from trusted vendors',
    confidence: 95,
    avgTime: '320ms',
    integrations: [],
    recentActivity: [
      { status: 'success', message: 'Successfully processed invoice #4821' },
      { status: 'success', message: 'Validated vendor ABC Corp' },
      { status: 'warning', message: 'Warning: Amount exceeds threshold' },
    ],
    naturalLanguage: 'When an invoice arrives from a trusted vendor and the total is under $500, automatically approve it without manual review.',
    logicSummary: 'When an invoice arrives from a trusted vendor and the total is under $500, automatically approve it without manual review.',
    logic: {
      when: 'Invoice reaches Validation & Exceptions stage',
      conditions: [
        { id: 'c1-1', field: 'Vendor', operator: 'is in', value: 'Trusted vendors list' },
        { id: 'c1-2', field: 'Amount', operator: '<', value: '500' },
      ],
      actions: [
        { id: 'a1-1', action: 'Auto-approve invoice', details: '' },
        { id: 'a1-2', action: 'Skip manual review', details: '' },
      ],
    },
    entities: ['All entities'],
    vendors: ['Trusted vendors'],
    conflictsCount: 0,
    simulationSummary: {
      invoicesEvaluated: 2134,
      wouldApply: 182,
      autoApply: 120,
      suggest: 62,
      observe: 0,
    },
    simulationInvoices: [
      {
        id: 'sim-1',
        invoiceNumber: 'INV-2025-001',
        supplier: 'Acme Corp',
        date: '2025-01-15',
        amount: '$450.00',
        outcome: 'Would auto-approve',
        hasConflict: false,
        explanation: 'Matched because vendor is trusted and amount ($450) < $500.',
      },
      {
        id: 'sim-2',
        invoiceNumber: 'INV-2025-002',
        supplier: 'TechSupply Inc',
        date: '2025-01-14',
        amount: '$320.00',
        outcome: 'Would auto-approve',
        hasConflict: false,
        explanation: 'Vendor is in trusted list, amount ($320) is under threshold.',
      },
      {
        id: 'sim-3',
        invoiceNumber: 'INV-2025-003',
        supplier: 'Office Depot',
        date: '2025-01-13',
        amount: '$499.99',
        outcome: 'Would auto-approve',
        hasConflict: true,
        conflictWith: 'Flag duplicate invoices',
        explanation: 'Would approve but conflicts with duplicate detection rule.',
      },
      {
        id: 'sim-4',
        invoiceNumber: 'INV-2025-004',
        supplier: 'New Vendor LLC',
        date: '2025-01-12',
        amount: '$250.00',
        outcome: 'No action',
        hasConflict: false,
        explanation: 'Vendor is not in trusted list, instruction does not apply.',
      },
      {
        id: 'sim-5',
        invoiceNumber: 'INV-2025-005',
        supplier: 'Acme Corp',
        date: '2025-01-11',
        amount: '$750.00',
        outcome: 'Would suggest',
        hasConflict: false,
        explanation: 'Vendor is trusted but amount ($750) exceeds $500 threshold.',
      },
    ],
    liveSummary: {
      triggersLast24h: 42,
      autoApplied: 30,
      overriddenByAP: 3,
      avgDecisionTime: '1.2s',
    },
    liveEvents: [
      {
        id: 'live-1',
        time: '14:32:15',
        invoiceNumber: 'INV-2025-089',
        supplier: 'TechSupply Inc',
        action: 'Auto-approve',
        outcome: 'Accepted',
        hasConflict: false,
        explanation: 'Vendor is in trusted list, amount $320 is under threshold.',
      },
      {
        id: 'live-2',
        time: '14:28:42',
        invoiceNumber: 'INV-2025-088',
        supplier: 'Acme Corp',
        action: 'Auto-approve',
        outcome: 'Accepted',
        hasConflict: false,
        explanation: 'Matched: trusted vendor, amount $480 < $500.',
      },
      {
        id: 'live-3',
        time: '14:15:03',
        invoiceNumber: 'INV-2025-087',
        supplier: 'Office Depot',
        action: 'Auto-approve',
        outcome: 'Overridden',
        hasConflict: true,
        explanation: 'Auto-approved but AP overrode due to duplicate suspicion.',
      },
      {
        id: 'live-4',
        time: '13:58:21',
        invoiceNumber: 'INV-2025-086',
        supplier: 'TechSupply Inc',
        action: 'Suggest',
        outcome: 'Pending',
        hasConflict: false,
        explanation: 'Amount $520 slightly over threshold, suggested for review.',
      },
      {
        id: 'live-5',
        time: '13:42:09',
        invoiceNumber: 'INV-2025-085',
        supplier: 'Acme Corp',
        action: 'Auto-approve',
        outcome: 'Accepted',
        hasConflict: false,
        explanation: 'Trusted vendor, amount $199 well under threshold.',
      },
    ],
  },
  {
    id: '2',
    name: 'Flag duplicate invoices',
    type: 'exception',
    status: 'Active',
    agent: 'Validation Agent',
    stage: 'Validation & Exceptions',
    processed: 892,
    success: 880,
    failed: 12,
    scope: 'All vendors • 30-day window',
    mode: 'Suggest',
    description: 'Detect and flag potential duplicate invoices within 30-day window',
    confidence: 78,
    avgTime: '450ms',
    integrations: [],
    recentActivity: [
      { status: 'success', message: 'Flagged duplicate INV-2024-8832' },
      { status: 'error', message: 'Failed to process batch #442' },
      { status: 'success', message: 'Cleared 12 false positives' },
    ],
    naturalLanguage: 'Check all incoming invoices against invoices received in the last 30 days. If a potential duplicate is found based on vendor, amount, and invoice number similarity, flag it for manual review.',
    logicSummary: 'Check all incoming invoices against invoices received in the last 30 days. If a potential duplicate is found, flag it for manual review.',
    logic: {
      when: 'Invoice reaches Validation & Exceptions stage',
      conditions: [
        { id: 'c2-1', field: 'Invoice number', operator: 'contains', value: 'existing pattern' },
        { id: 'c2-2', field: 'Vendor', operator: 'equals', value: 'Same vendor (30-day window)' },
        { id: 'c2-3', field: 'Amount', operator: 'equals', value: 'within 1% tolerance' },
      ],
      actions: [
        { id: 'a2-1', action: 'Flag exception', details: 'Potential duplicate' },
        { id: 'a2-2', action: 'Add to queue', details: 'Exception queue' },
        { id: 'a2-3', action: 'Notify assigned reviewer', details: '' },
      ],
    },
    entities: ['All entities'],
    vendors: ['All vendors'],
    conflictsCount: 1,
    conflictsSummary: "overlaps with 'Auto-approve small vendors'",
  },
  {
    id: '3',
    name: 'Route to department heads',
    type: 'routing',
    status: 'Active',
    agent: 'Routing Agent',
    stage: 'Non-PO Approval Workflow',
    processed: 567,
    success: 539,
    failed: 28,
    scope: 'Invoices > $5,000',
    mode: 'Suggest',
    description: 'Route invoices over $5000 to respective department heads for approval',
    confidence: 92,
    avgTime: '180ms',
    integrations: ['EMAIL'],
    recentActivity: [
      { status: 'success', message: 'Routed INV-2024-9001 to Finance' },
      { status: 'success', message: 'Notified J. Smith via email' },
      { status: 'warning', message: 'Pending approval for 3 invoices' },
    ],
    naturalLanguage: 'For non-PO invoices exceeding $5,000, automatically route to the appropriate department head based on the cost center. Send email notification to the approver.',
    logicSummary: 'For non-PO invoices exceeding $5,000, automatically route to the appropriate department head and send email notification.',
    logic: {
      when: 'Invoice enters Non-PO Approval Workflow',
      conditions: [
        { id: 'c3-1', field: 'Amount', operator: '>', value: '5000' },
        { id: 'c3-2', field: 'Invoice type', operator: 'equals', value: 'Non-PO' },
        { id: 'c3-3', field: 'Cost center', operator: 'is not', value: 'empty' },
      ],
      actions: [
        { id: 'a3-1', action: 'Route to approver', details: 'Department head' },
        { id: 'a3-2', action: 'Send email notification', details: 'Approver' },
      ],
    },
    entities: ['All entities'],
    vendors: ['All vendors'],
    conflictsCount: 0,
  },
  {
    id: '4',
    name: 'Validate PO matching',
    type: 'validation',
    status: 'Active',
    agent: 'Matching Agent',
    stage: 'PO Matching',
    processed: 2341,
    success: 2015,
    failed: 326,
    scope: 'All PO invoices • 3% tolerance',
    mode: 'Suggest',
    description: 'Check all invoices against purchase orders with 3% tolerance',
    confidence: 88,
    avgTime: '520ms',
    integrations: ['ERP'],
    recentActivity: [
      { status: 'success', message: 'Matched INV-2024-9102 to PO-8821' },
      { status: 'error', message: 'Variance exceeded on INV-2024-9098' },
      { status: 'success', message: 'Auto-resolved 15 minor variances' },
    ],
    naturalLanguage: 'Match all invoices with referenced purchase orders from the ERP system. Allow a 3% variance tolerance for price differences. Auto-resolve minor variances and flag significant mismatches.',
    logicSummary: 'Match all invoices with referenced purchase orders, allowing 3% variance tolerance. Auto-resolve minor variances and flag significant mismatches.',
    logic: {
      when: 'Invoice reaches PO Matching stage',
      conditions: [
        { id: 'c4-1', field: 'Invoice type', operator: 'equals', value: 'PO Invoice' },
        { id: 'c4-2', field: 'Amount', operator: '<=', value: '3% variance' },
      ],
      actions: [
        { id: 'a4-1', action: 'Auto-approve invoice', details: 'If variance ≤ 3%' },
        { id: 'a4-2', action: 'Flag exception', details: 'If variance > 3%' },
      ],
    },
    entities: ['All entities'],
    vendors: ['All vendors'],
    conflictsCount: 0,
  },
];
